# Generated by Django 3.2.10 on 2022-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='capital',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
