# Generated by Django 3.2.10 on 2022-05-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.CharField(max_length=40)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.state')),
            ],
        ),
        migrations.CreateModel(
            name='Language2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=40)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='apis.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='con', to='apis.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state', to='apis.state')),
            ],
        ),
    ]
