# Generated by Django 3.2.10 on 2022-05-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_language2_population2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language2',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='apis.city'),
        ),
        migrations.AlterField(
            model_name='language2',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='con', to='apis.country'),
        ),
        migrations.AlterField(
            model_name='language2',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state', to='apis.state'),
        ),
        migrations.AlterField(
            model_name='population2',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.city'),
        ),
        migrations.AlterField(
            model_name='population2',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.country'),
        ),
        migrations.AlterField(
            model_name='population2',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.state'),
        ),
    ]
