# Generated by Django 3.2.10 on 2022-05-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20220520_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population2',
            name='city',
        ),
        migrations.RemoveField(
            model_name='population2',
            name='country',
        ),
        migrations.RemoveField(
            model_name='population2',
            name='language',
        ),
        migrations.RemoveField(
            model_name='population2',
            name='state',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.RemoveField(
            model_name='language',
            name='main_location',
        ),
        migrations.RemoveField(
            model_name='population',
            name='main_location',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.city'),
        ),
        migrations.AddField(
            model_name='population',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.country'),
        ),
        migrations.AddField(
            model_name='population',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language', to='apis.language'),
        ),
        migrations.AddField(
            model_name='population',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.state'),
        ),
        migrations.AlterField(
            model_name='population',
            name='population',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Language2',
        ),
        migrations.DeleteModel(
            name='Population2',
        ),
    ]
