# Generated by Django 3.2.10 on 2022-05-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20220520_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='apis.city'),
        ),
        migrations.AlterField(
            model_name='population',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country', to='apis.country'),
        ),
        migrations.AlterField(
            model_name='population',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state', to='apis.state'),
        ),
    ]
